name: final_glamr
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+2

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  purchases_flutter: ^8.5.2
  # Dependencies for camera access
  camera: ^0.10.0
  flutter_dotenv: ^5.1.0
  dropdown_button2: ^2.3.9

  image_picker: ^0.8.5+3

  # For making HTTP requests to the API
  http: ^0.13.5

  # For custom fonts (e.g., Google Fonts if needed)
  google_fonts: ^2.3.1

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.14
  webview_flutter: ^4.10.0
  camera_avfoundation: ^0.9.17+5
  flutter_native_splash: ^2.4.3

dependency_overriders:
  path_provider_windows: 0.0.0
  win32: 0.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/glamr_black_background.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/lululemon.png
    - assets/skims.png
    - assets/gymshark.png
    - assets/alo.png
    - assets/gap.png
    - assets/nike.png
    - assets/uniqlo.jpeg

flutter_native_splash:
  # Background image to use for the splash screen
  android: true
  ios: true
#  background_image: "assets/splash_screen.png"
  image: "assets/glamr_black_background_splash.png"
#  fullscreen: true
  color: "#000000"
#  fill: true
  # Android 12 specific settings
  android_12:
    # Specify the background color or an image for Android 12 devices
    image: "assets/glamr_black_background_splash.png"
    icon_background_color: "#000000" # Adjust to match your app's theme (optional)

